services:
  ingestion:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ingestion
    depends_on:
      - pgdatabase
    env_file:
      - ./.env
    volumes:
      - .:/app
    restart: unless-stopped
  pgdatabase:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    env_file:
      - ./.env
    depends_on:
      - pgdatabase
    restart: unless-stopped
    volumes:
      - pgadmin:/var/lib/pgadmin
  
volumes:
  pgdata:
  pgadmin: